# Set true color
set-option -sa terminal-overrides ",xterm*:Tc"

set -g mouse on

# Copy like vim-mode
set-option -g mode-keys vi
bind-key -T copy-mode-vi 'v'   send -X rectangle-on \; send -X begin-selection   # Begin selection in copy mode
bind-key -T copy-mode-vi 'C-v' send -X rectangle-off \; send -X begin-selection  # Begin selection in copy mode
bind-key -T copy-mode-vi 'y'   send -X copy-selection-and-cancel                 # Yank selection in copy mode

bind-key -T copy-mode-vi Escape {
    if-shell -F "#{selection_present}" {
        # true
        send-keys -X clear-selection
    } {
        # false
        send-keys -X cancel
    }
}

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'dracula/tmux'

# Snippet for smart-splits.nvim
# '@pane-is-vim' is a pane-local option that is set by the plugin on load,
# and unset when Neovim exits or suspends; note that this means you'll probably
# not want to lazy-load smart-splits.nvim, as the variable won't be set until
# the plugin is loaded

# Smart pane switching with awareness of Neovim splits.
bind-key -n C-h if -F '#{@pane-is-vim}' 'send-keys C-h'  'select-pane -L'
bind-key -n C-j if -F '#{@pane-is-vim}' 'send-keys C-j'  'select-pane -D'
bind-key -n C-k if -F '#{@pane-is-vim}' 'send-keys C-k'  'select-pane -U'
bind-key -n C-l if -F '#{@pane-is-vim}' 'send-keys C-l'  'select-pane -R'

# Smart pane resizing with awareness of Neovim splits.
bind-key -n C-S-H if -F '#{@pane-is-vim}' 'send-keys M-h' 'resize-pane -L 3'
bind-key -n C-S-J if -F '#{@pane-is-vim}' 'send-keys M-j' 'resize-pane -D 3'
bind-key -n C-S-L if -F '#{@pane-is-vim}' 'send-keys M-l' 'resize-pane -R 3'
bind-key -n C-S-K if -F '#{@pane-is-vim}' 'send-keys M-k' 'resize-pane -U 3'

bind-key -n C-\\ if -F '#{@pane-is-vim}' 'send-keys C-\\\\'  'select-pane -l'

bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
bind-key -T copy-mode-vi C-\\ select-pane -l

# Resurrect Session
set -g @continuum-restore 'on'

# Tmux-Menus
set -g @menus_location_x R
set -g @menus_location_y P

# Yank Opts
set -g @yank_action 'copy-pipe'

# Themes
set -g @dracula-plugins "cpu-usage ram-usage time"
set -g @dracula-show-left-icon 🌲
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-cpu-usage-label ""
set -g @dracula-ram-usage-label ""
# Kiloometer Daytime, I hate americans
set -g @dracula-show-timezone false
set -g @dracula-day-month true
set -g @dracula-military-time true

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
