#!/usr/bin/env sh

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Setup Workspaces
i=1
n=`bspc query -M | wc -l`  # count number of lines in bspwm's monitor list
per=5          # number of desktops per monitor
for monitor in `bspc query -M`; do
    bspc monitor $monitor -d `seq $i $(( i + per - 1 ))` 
    # seq is end-inclusive; `seq 1 $((1+2))` returns "1 2 3"
    i=$(( i + per ))
done

# =================
# Set Border Colors
# =================
bspc config normal_border_color \#bfbfbf
bspc config active_border_color \#4d4d4d
bspc config focused_border_color \#ff79c6
bspc config presel_feedback_color \#ff79c6

# ==============
# Other programs
# ==============

# Polybar Setup
$HOME/.config/polybar/launch_polybar

pextra &
