import = ["/home/pini/.config/alacritty/dracula.toml"]

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[window.padding]
x = 0
y = 0
